# railway.toml
[build]
builder = "dockerfile"

dockerfilePath = "./EcoFashionBackEnd/Dockerfile"

[deploy]
startCommand = "./EcoFashionBackEnd"
restartPolicyType = "always"
healthcheckPath = "/health" # Giữ nguyên nếu bạn có endpoint health check